// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// JupgingLog is the predicate function for jupginglog builders.
type JupgingLog func(*sql.Selector)

// Member is the predicate function for member builders.
type Member func(*sql.Selector)
