// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"junction/internal/model/ent/jupginglog"
	"junction/internal/model/ent/member"
	"junction/internal/model/ent/predicate"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// JupgingLogQuery is the builder for querying JupgingLog entities.
type JupgingLogQuery struct {
	config
	ctx        *QueryContext
	order      []jupginglog.OrderOption
	inters     []Interceptor
	predicates []predicate.JupgingLog
	withMember *MemberQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the JupgingLogQuery builder.
func (jlq *JupgingLogQuery) Where(ps ...predicate.JupgingLog) *JupgingLogQuery {
	jlq.predicates = append(jlq.predicates, ps...)
	return jlq
}

// Limit the number of records to be returned by this query.
func (jlq *JupgingLogQuery) Limit(limit int) *JupgingLogQuery {
	jlq.ctx.Limit = &limit
	return jlq
}

// Offset to start from.
func (jlq *JupgingLogQuery) Offset(offset int) *JupgingLogQuery {
	jlq.ctx.Offset = &offset
	return jlq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (jlq *JupgingLogQuery) Unique(unique bool) *JupgingLogQuery {
	jlq.ctx.Unique = &unique
	return jlq
}

// Order specifies how the records should be ordered.
func (jlq *JupgingLogQuery) Order(o ...jupginglog.OrderOption) *JupgingLogQuery {
	jlq.order = append(jlq.order, o...)
	return jlq
}

// QueryMember chains the current query on the "member" edge.
func (jlq *JupgingLogQuery) QueryMember() *MemberQuery {
	query := (&MemberClient{config: jlq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := jlq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := jlq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(jupginglog.Table, jupginglog.FieldID, selector),
			sqlgraph.To(member.Table, member.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, jupginglog.MemberTable, jupginglog.MemberColumn),
		)
		fromU = sqlgraph.SetNeighbors(jlq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first JupgingLog entity from the query.
// Returns a *NotFoundError when no JupgingLog was found.
func (jlq *JupgingLogQuery) First(ctx context.Context) (*JupgingLog, error) {
	nodes, err := jlq.Limit(1).All(setContextOp(ctx, jlq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{jupginglog.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (jlq *JupgingLogQuery) FirstX(ctx context.Context) *JupgingLog {
	node, err := jlq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first JupgingLog ID from the query.
// Returns a *NotFoundError when no JupgingLog ID was found.
func (jlq *JupgingLogQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = jlq.Limit(1).IDs(setContextOp(ctx, jlq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{jupginglog.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (jlq *JupgingLogQuery) FirstIDX(ctx context.Context) int {
	id, err := jlq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single JupgingLog entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one JupgingLog entity is found.
// Returns a *NotFoundError when no JupgingLog entities are found.
func (jlq *JupgingLogQuery) Only(ctx context.Context) (*JupgingLog, error) {
	nodes, err := jlq.Limit(2).All(setContextOp(ctx, jlq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{jupginglog.Label}
	default:
		return nil, &NotSingularError{jupginglog.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (jlq *JupgingLogQuery) OnlyX(ctx context.Context) *JupgingLog {
	node, err := jlq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only JupgingLog ID in the query.
// Returns a *NotSingularError when more than one JupgingLog ID is found.
// Returns a *NotFoundError when no entities are found.
func (jlq *JupgingLogQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = jlq.Limit(2).IDs(setContextOp(ctx, jlq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{jupginglog.Label}
	default:
		err = &NotSingularError{jupginglog.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (jlq *JupgingLogQuery) OnlyIDX(ctx context.Context) int {
	id, err := jlq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of JupgingLogs.
func (jlq *JupgingLogQuery) All(ctx context.Context) ([]*JupgingLog, error) {
	ctx = setContextOp(ctx, jlq.ctx, ent.OpQueryAll)
	if err := jlq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*JupgingLog, *JupgingLogQuery]()
	return withInterceptors[[]*JupgingLog](ctx, jlq, qr, jlq.inters)
}

// AllX is like All, but panics if an error occurs.
func (jlq *JupgingLogQuery) AllX(ctx context.Context) []*JupgingLog {
	nodes, err := jlq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of JupgingLog IDs.
func (jlq *JupgingLogQuery) IDs(ctx context.Context) (ids []int, err error) {
	if jlq.ctx.Unique == nil && jlq.path != nil {
		jlq.Unique(true)
	}
	ctx = setContextOp(ctx, jlq.ctx, ent.OpQueryIDs)
	if err = jlq.Select(jupginglog.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (jlq *JupgingLogQuery) IDsX(ctx context.Context) []int {
	ids, err := jlq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (jlq *JupgingLogQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, jlq.ctx, ent.OpQueryCount)
	if err := jlq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, jlq, querierCount[*JupgingLogQuery](), jlq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (jlq *JupgingLogQuery) CountX(ctx context.Context) int {
	count, err := jlq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (jlq *JupgingLogQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, jlq.ctx, ent.OpQueryExist)
	switch _, err := jlq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (jlq *JupgingLogQuery) ExistX(ctx context.Context) bool {
	exist, err := jlq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the JupgingLogQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (jlq *JupgingLogQuery) Clone() *JupgingLogQuery {
	if jlq == nil {
		return nil
	}
	return &JupgingLogQuery{
		config:     jlq.config,
		ctx:        jlq.ctx.Clone(),
		order:      append([]jupginglog.OrderOption{}, jlq.order...),
		inters:     append([]Interceptor{}, jlq.inters...),
		predicates: append([]predicate.JupgingLog{}, jlq.predicates...),
		withMember: jlq.withMember.Clone(),
		// clone intermediate query.
		sql:  jlq.sql.Clone(),
		path: jlq.path,
	}
}

// WithMember tells the query-builder to eager-load the nodes that are connected to
// the "member" edge. The optional arguments are used to configure the query builder of the edge.
func (jlq *JupgingLogQuery) WithMember(opts ...func(*MemberQuery)) *JupgingLogQuery {
	query := (&MemberClient{config: jlq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	jlq.withMember = query
	return jlq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		StartDate string `json:"startDate,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.JupgingLog.Query().
//		GroupBy(jupginglog.FieldStartDate).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (jlq *JupgingLogQuery) GroupBy(field string, fields ...string) *JupgingLogGroupBy {
	jlq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &JupgingLogGroupBy{build: jlq}
	grbuild.flds = &jlq.ctx.Fields
	grbuild.label = jupginglog.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		StartDate string `json:"startDate,omitempty"`
//	}
//
//	client.JupgingLog.Query().
//		Select(jupginglog.FieldStartDate).
//		Scan(ctx, &v)
func (jlq *JupgingLogQuery) Select(fields ...string) *JupgingLogSelect {
	jlq.ctx.Fields = append(jlq.ctx.Fields, fields...)
	sbuild := &JupgingLogSelect{JupgingLogQuery: jlq}
	sbuild.label = jupginglog.Label
	sbuild.flds, sbuild.scan = &jlq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a JupgingLogSelect configured with the given aggregations.
func (jlq *JupgingLogQuery) Aggregate(fns ...AggregateFunc) *JupgingLogSelect {
	return jlq.Select().Aggregate(fns...)
}

func (jlq *JupgingLogQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range jlq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, jlq); err != nil {
				return err
			}
		}
	}
	for _, f := range jlq.ctx.Fields {
		if !jupginglog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if jlq.path != nil {
		prev, err := jlq.path(ctx)
		if err != nil {
			return err
		}
		jlq.sql = prev
	}
	return nil
}

func (jlq *JupgingLogQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*JupgingLog, error) {
	var (
		nodes       = []*JupgingLog{}
		_spec       = jlq.querySpec()
		loadedTypes = [1]bool{
			jlq.withMember != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*JupgingLog).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &JupgingLog{config: jlq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, jlq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := jlq.withMember; query != nil {
		if err := jlq.loadMember(ctx, query, nodes, nil,
			func(n *JupgingLog, e *Member) { n.Edges.Member = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (jlq *JupgingLogQuery) loadMember(ctx context.Context, query *MemberQuery, nodes []*JupgingLog, init func(*JupgingLog), assign func(*JupgingLog, *Member)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*JupgingLog)
	for i := range nodes {
		fk := nodes[i].MemberID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(member.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "member_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (jlq *JupgingLogQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := jlq.querySpec()
	_spec.Node.Columns = jlq.ctx.Fields
	if len(jlq.ctx.Fields) > 0 {
		_spec.Unique = jlq.ctx.Unique != nil && *jlq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, jlq.driver, _spec)
}

func (jlq *JupgingLogQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(jupginglog.Table, jupginglog.Columns, sqlgraph.NewFieldSpec(jupginglog.FieldID, field.TypeInt))
	_spec.From = jlq.sql
	if unique := jlq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if jlq.path != nil {
		_spec.Unique = true
	}
	if fields := jlq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, jupginglog.FieldID)
		for i := range fields {
			if fields[i] != jupginglog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if jlq.withMember != nil {
			_spec.Node.AddColumnOnce(jupginglog.FieldMemberID)
		}
	}
	if ps := jlq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := jlq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := jlq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := jlq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (jlq *JupgingLogQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(jlq.driver.Dialect())
	t1 := builder.Table(jupginglog.Table)
	columns := jlq.ctx.Fields
	if len(columns) == 0 {
		columns = jupginglog.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if jlq.sql != nil {
		selector = jlq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if jlq.ctx.Unique != nil && *jlq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range jlq.predicates {
		p(selector)
	}
	for _, p := range jlq.order {
		p(selector)
	}
	if offset := jlq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := jlq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// JupgingLogGroupBy is the group-by builder for JupgingLog entities.
type JupgingLogGroupBy struct {
	selector
	build *JupgingLogQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (jlgb *JupgingLogGroupBy) Aggregate(fns ...AggregateFunc) *JupgingLogGroupBy {
	jlgb.fns = append(jlgb.fns, fns...)
	return jlgb
}

// Scan applies the selector query and scans the result into the given value.
func (jlgb *JupgingLogGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, jlgb.build.ctx, ent.OpQueryGroupBy)
	if err := jlgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*JupgingLogQuery, *JupgingLogGroupBy](ctx, jlgb.build, jlgb, jlgb.build.inters, v)
}

func (jlgb *JupgingLogGroupBy) sqlScan(ctx context.Context, root *JupgingLogQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(jlgb.fns))
	for _, fn := range jlgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*jlgb.flds)+len(jlgb.fns))
		for _, f := range *jlgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*jlgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := jlgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// JupgingLogSelect is the builder for selecting fields of JupgingLog entities.
type JupgingLogSelect struct {
	*JupgingLogQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (jls *JupgingLogSelect) Aggregate(fns ...AggregateFunc) *JupgingLogSelect {
	jls.fns = append(jls.fns, fns...)
	return jls
}

// Scan applies the selector query and scans the result into the given value.
func (jls *JupgingLogSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, jls.ctx, ent.OpQuerySelect)
	if err := jls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*JupgingLogQuery, *JupgingLogSelect](ctx, jls.JupgingLogQuery, jls, jls.inters, v)
}

func (jls *JupgingLogSelect) sqlScan(ctx context.Context, root *JupgingLogQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(jls.fns))
	for _, fn := range jls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*jls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := jls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
